# Generated by Django 4.1.7 on 2023-03-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0002_alter_students_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesubmit',
            name='sessionkey',
            field=models.CharField(default='', max_length=50),
        ),
    ]
