# Generated by Django 4.1.7 on 2023-04-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0003_attendancesubmit_sessionkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AddField(
            model_name='students',
            name='lrn',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
