# Generated by Django 4.1.7 on 2023-04-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0004_remove_students_id_students_lrn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='lrn',
            new_name='id',
        ),
    ]
