# Generated by Django 4.1.7 on 2023-04-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0005_rename_lrn_students_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='id',
            new_name='lrn',
        ),
    ]
