# Generated by Django 4.1.7 on 2023-04-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0006_rename_id_students_lrn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absentdate', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.students')),
            ],
        ),
    ]
