# Generated by Django 4.1.7 on 2023-04-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0009_latelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latelist',
            name='attendancesubmit',
        ),
        migrations.AddField(
            model_name='latelist',
            name='submittime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
