# Generated by Django 4.1.7 on 2023-04-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0010_remove_latelist_attendancesubmit_latelist_submittime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesubmit',
            name='email',
        ),
        migrations.AddField(
            model_name='attendancesubmit',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_attendance.students'),
        ),
    ]
