# Generated by Django 4.1.7 on 2023-04-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0011_remove_attendancesubmit_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesubmit',
            name='student',
        ),
        migrations.AddField(
            model_name='attendancesubmit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
