# Generated by Django 4.1.7 on 2023-04-15 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0012_remove_attendancesubmit_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='attendancesubmit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_attendance.attendancesubmit'),
        ),
    ]
