# Generated by Django 4.1.7 on 2023-04-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0014_alter_attendancesubmit_submit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesubmit',
            name='submit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
