# Generated by Django 4.1.7 on 2023-04-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0015_alter_attendancesubmit_submit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='attendancesubmit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_attendance.attendancesubmit'),
        ),
    ]
