# Generated by Django 4.1.7 on 2023-04-30 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0016_alter_students_attendancesubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='startingtime',
            name='lastday',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 9, 50, 56, 656102)),
        ),
    ]
