# Generated by Django 4.1.4 on 2023-01-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0002_attendance_email_attendance_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('grade', models.IntegerField(default=0)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('classnumber', models.IntegerField(default=0)),
                ('lates', models.IntegerField(default=0)),
                ('absents', models.IntegerField(default=0)),
            ],
        ),
    ]
