# Generated by Django 4.1.5 on 2023-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0003_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIntegers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
