# Generated by Django 4.1.5 on 2023-01-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0004_dailyintegers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyIntegers',
            new_name='DailyInteger',
        ),
    ]
