# Generated by Django 4.1.5 on 2023-02-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0007_remove_startingtime_startinghour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startingtime',
            old_name='startTime',
            new_name='starttime',
        ),
    ]
