# Generated by Django 4.1.5 on 2023-02-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0008_rename_starttime_startingtime_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='spr',
            field=models.IntegerField(default=0),
        ),
    ]
