# Generated by Django 4.1.5 on 2023-02-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0010_todayattendance_rename_attendance_attendancesubmit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodayAttendance',
        ),
        migrations.AddField(
            model_name='students',
            name='absenttoday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='students',
            name='latetoday',
            field=models.BooleanField(default=False),
        ),
    ]
