# Generated by Django 4.1.5 on 2023-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0011_delete_todayattendance_students_absenttoday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
    ]
