# Generated by Django 4.1.5 on 2023-02-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0012_alter_students_email_alter_students_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
