# Generated by Django 4.1.5 on 2023-02-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0013_teacherpasswords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherPasswords',
        ),
    ]
