# Generated by Django 4.1.5 on 2023-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0014_delete_teacherpasswords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
