# Generated by Django 4.1.5 on 2023-03-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0017_alter_students_absents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='absents',
            field=models.FloatField(default=0),
        ),
    ]
