# Generated by Django 4.1.5 on 2023-03-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0019_sections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sections',
            new_name='SectionList',
        ),
    ]
