# Generated by Django 4.1.5 on 2023-03-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0021_sectionlist_highschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionlist',
            name='highschool',
            field=models.CharField(default='shs', max_length=3),
        ),
    ]
